using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace UnityToolManagerGenerator.Tests;

public class StatisticsMenuItemGeneratorTests
{
    private const string SourceText = @"
namespace TestNamespace;

public static partial class MyTools
{
    [Generators.StatisticsMenuItem(""Tools/Statistics/Reset"")]
    public static void ResetStats() { }
}";

    private const string ExpectedGeneratedClassText = @"// <auto-generated/>

using UnityEditor;

namespace TestNamespace;

partial class MyTools
{
    [MenuItem(""Tools/Statistics/Reset"")]
    public static void ResetStats_MenuItem()
    {
        Generators.StatisticsMenuItemHelper.SendStatistics(""ResetStats"");
        ResetStats();
    }
}
";

    [Fact]
    public void GenerateMenuItemMethod()
    {
        var generator = new StatisticsMenuItemGenerator();

        var driver = CSharpGeneratorDriver.Create(generator);

        var compilation = CSharpCompilation.Create(nameof(StatisticsMenuItemGeneratorTests),
            new[] { CSharpSyntaxTree.ParseText(SourceText) },
            new[]
            {
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            });

        var runResult = driver.RunGenerators(compilation).GetRunResult();

        var generatedFileSyntax = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("MyTools.StatisticsMenuItem.g.cs"));

        Assert.Equal(ExpectedGeneratedClassText, generatedFileSyntax.GetText().ToString(),
            ignoreLineEndingDifferences: true);
    }


    private const string MultipleMethodsSourceText = @"
namespace TestNamespace;

public static partial class StatsWindow
{
    [Generators.StatisticsMenuItem(""Tools/Statistics/Show"")]
    public static void ShowStats() { }

    [Generators.StatisticsMenuItem(""Tools/Statistics/Clear"")]
    public static void ClearStats() { }
}";

    private const string ExpectedMultipleMethodsGeneratedText = @"// <auto-generated/>

using UnityEditor;

namespace TestNamespace;

partial class StatsWindow
{
    [MenuItem(""Tools/Statistics/Show"")]
    public static void ShowStats_MenuItem()
    {
        Generators.StatisticsMenuItemHelper.SendStatistics(""ShowStats"");
        ShowStats();
    }
    [MenuItem(""Tools/Statistics/Clear"")]
    public static void ClearStats_MenuItem()
    {
        Generators.StatisticsMenuItemHelper.SendStatistics(""ClearStats"");
        ClearStats();
    }
}
";

    [Fact]
    public void GenerateMultipleMenuItemMethods()
    {
        var generator = new StatisticsMenuItemGenerator();

        var driver = CSharpGeneratorDriver.Create(generator);

        var compilation = CSharpCompilation.Create(nameof(StatisticsMenuItemGeneratorTests),
            new[] { CSharpSyntaxTree.ParseText(MultipleMethodsSourceText) },
            new[]
            {
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            });

        var runResult = driver.RunGenerators(compilation).GetRunResult();

        var generatedFileSyntax = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("StatsWindow.StatisticsMenuItem.g.cs"));

        Assert.Equal(ExpectedMultipleMethodsGeneratedText, generatedFileSyntax.GetText().ToString(),
            ignoreLineEndingDifferences: true);
    }
}
