using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;


namespace UnityToolManagerGenerator;

/// <summary>
/// A source generator that creates Unity MenuItem-attributed wrapper methods for methods annotated with [StatisticsMenuItem].
/// The generated methods send usage statistics (method name + datetime) to a GAS API before calling the original method.
/// </summary>
[Generator]
public class StatisticsMenuItemGenerator : IIncrementalGenerator
{
    private const string Namespace = "Generators";
    private const string AttributeName = "StatisticsMenuItemAttribute";

    private const string AttributeSourceCode = $@"// <auto-generated/>

namespace {Namespace}
{{
    [System.AttributeUsage(System.AttributeTargets.Method)]
    public class {AttributeName} : System.Attribute
    {{
        public string MenuPath {{ get; }}
        public {AttributeName}(string menuPath)
        {{
            MenuPath = menuPath;
        }}
    }}
}}";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Add the marker attribute to the compilation.
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource(
                "StatisticsMenuItemAttribute.g.cs",
                SourceText.From(AttributeSourceCode, Encoding.UTF8));
        });

        // Filter methods annotated with the [StatisticsMenuItem] attribute.
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                (s, _) => s is MethodDeclarationSyntax,
                (ctx, _) => GetMethodDeclarationForSourceGen(ctx))
            .Where(t => t.found)
            .Select((t, _) => (t.method, t.menuPath));

        // Generate the source code.
        context.RegisterSourceOutput(context.CompilationProvider.Combine(provider.Collect()),
            (ctx, t) => GenerateCode(ctx, t.Left, t.Right));
    }

    private static (MethodDeclarationSyntax method, bool found, string menuPath) GetMethodDeclarationForSourceGen(
        GeneratorSyntaxContext context)
    {
        var methodDeclarationSyntax = (MethodDeclarationSyntax)context.Node;

        foreach (AttributeListSyntax attributeListSyntax in methodDeclarationSyntax.AttributeLists)
        foreach (AttributeSyntax attributeSyntax in attributeListSyntax.Attributes)
        {
            if (context.SemanticModel.GetSymbolInfo(attributeSyntax).Symbol is not IMethodSymbol attributeSymbol)
                continue;

            string attributeName = attributeSymbol.ContainingType.ToDisplayString();

            if (attributeName == $"{Namespace}.{AttributeName}")
            {
                // Extract the menu path from the attribute argument.
                var menuPath = "";
                if (attributeSyntax.ArgumentList?.Arguments.Count > 0)
                {
                    var expression = attributeSyntax.ArgumentList.Arguments[0].Expression;
                    if (expression is LiteralExpressionSyntax literal)
                    {
                        menuPath = literal.Token.ValueText;
                    }
                }

                return (methodDeclarationSyntax, true, menuPath);
            }
        }

        return (methodDeclarationSyntax, false, "");
    }

    private void GenerateCode(SourceProductionContext context, Compilation compilation,
        ImmutableArray<(MethodDeclarationSyntax method, string menuPath)> methods)
    {
        // Group methods by their containing class.
        var grouped = methods
            .GroupBy(m =>
            {
                var semanticModel = compilation.GetSemanticModel(m.method.SyntaxTree);
                var methodSymbol = semanticModel.GetDeclaredSymbol(m.method) as IMethodSymbol;
                return methodSymbol?.ContainingType;
            }, SymbolEqualityComparer.Default)
            .Where(g => g.Key != null);

        foreach (var group in grouped)
        {
            var classSymbol = (INamedTypeSymbol)group.Key!;
            var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
            var className = classSymbol.Name;

            var methodsBuilder = new StringBuilder();
            foreach (var (method, menuPath) in group)
            {
                var methodName = method.Identifier.Text;
                methodsBuilder.AppendLine($@"        [MenuItem(""{menuPath}"")]");
                methodsBuilder.AppendLine($@"        public static void {methodName}_MenuItem()");
                methodsBuilder.AppendLine($@"        {{");
                methodsBuilder.AppendLine($@"            Generators.StatisticsMenuItemHelper.SendStatistics(""{methodName}"");");
                methodsBuilder.AppendLine($@"            {methodName}();");
                methodsBuilder.AppendLine($@"        }}");
            }

            var code = $@"// <auto-generated/>

using UnityEditor;

namespace {namespaceName}
{{
    partial class {className}
    {{
{methodsBuilder.ToString().TrimEnd()}
    }}
}}
";

            context.AddSource($"{className}.StatisticsMenuItem.g.cs", SourceText.From(code, Encoding.UTF8));
        }
    }
}
